version: "3.0"

scanning-settings:
  max-depth: 6
  exclude: []
  include-files: []
  system:
    targets: []

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: true
      cvss-severity: []

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - medium
        - critical
        - high
      exploitability:
        - medium
        - critical
        - high

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch

# Safety Security and License Configuration file
security: # configuration for the `safety check` command
  ignore-cvss-severity-below: 0 # A severity number between 0 and 10. Some helpful reference points: 9=ignore all vulnerabilities except CRITICAL severity. 7=ignore all vulnerabilities except CRITICAL
  ignore-cvss-unknown-severity: False # True or False. We recommend you set this to False.
  ignore-vulnerabilities: # Here you can list multiple specific vulnerabilities you want to ignore (optionally for a time period)
    # We recommend making use of the optional `reason` and `expires` keys for each vulnerability that you ignore.
    68477:
      reason: is only a raise condition
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    71608:
      reason: ProxyManager not used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    59071:
      reason: Tornado not directly used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    61949:
      reason: Tornado not directly used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    71956:
      reason: Tornado not directly used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    71957:
      reason: Tornado not directly used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    72236:
      reason: only used to setup the environment at the first time
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    71064:
      reason: requests not used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    70612:
      reason: jinja2 not used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    66742:
      reason: black only used in dev mode
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    64484:
      reason: bandit not used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    71636:
      reason: authlib not used
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable
    72132:
      reason: zipp not severe
      expires: "2025-12-31" # datetime string - date this ignore will expire, best practice to use this variable

  continue-on-vulnerability-error: False # Suppress non-zero exit codes when vulnerabilities are found. Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities
